# Generated by Django 5.2.4 on 2025-08-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0005_bulletinenvoilog'),
        ('users', '0002_customuser_first_login_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='hr_employees.employee'),
        ),
    ]
