# Generated by Django 5.2.4 on 2025-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_embauche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
