# Generated by Django 5.2.4 on 2025-07-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0002_alter_employee_date_embauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True),
        ),
    ]
