# Generated by Django 5.2.4 on 2025-07-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0003_alter_employee_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
