# Generated by Django 5.2.4 on 2025-08-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0005_bulletinenvoilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinenvoilog',
            name='employees_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
